services:
  web:
    image: nginx:1.27.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
      - ./app:/usr/share/nginx/html
    ports:
      - 8080:80

  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=root
      - POSTGRES_DB=project-database
    ports:
      - 5432:5432
    networks:
      - toler-express-apps

  auth-backend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-TolerTomas
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - postgres-db
    environment:
      # examples
      - DATABASE_URL=postgres://root:mysecretpassword@postgres-db/project-database
      # cambiar / borrar token
      - JWT_SECRET="kjghiwu8673t439847vn><72"(vgSJa7><)"
    privileged: true
    networks:
      - toler-express-apps

  file-server-backend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-microservice-TolerTomas
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - AUTH_SERVER_ADDRESS=auth-backend-app
      - AUTH_SERVER_USERNAME=file-server
      - AUTH_SERVER_PASSWORD=12345678
      - STORAGE_URL=/app-storage
    volumes:
      - ./app-storage:/app/storage
    networks:
      - toler-express-apps

networks:
  toler-express-apps:
    external: true

volumes:
  app-storage: