services:
  web:
    image: nginx:1.27.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log
      - ./app:/usr/share/nginx/html
    ports:
      - 8080:80


