services:

  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=root
      - POSTGRES_DB=project-database
    ports:
      - 5432:5432
    networks:
      - toler-express-apps

  auth-backend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-TolerTomas.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgres://root:mysecretpassword@postgres-db/project-database
      - JWT_SECRET="kjghiwu8673t439847vn><72"(vgSJa7><)"
    privileged: true
    networks:
      - toler-express-apps
    entrypoint: >
      /bin/sh -c "
      pnpm run db:push &&
      pnpm run dev"

  file-server-backend-app:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-microservice-TolerTomas.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - AUTH_SERVER_ADDRESS=auth-backend-app
      - AUTH_SERVER_USERNAME=file-server
      - AUTH_SERVER_PASSWORD=12345678
      - STORAGE_URL=app-storage
    depends_on:
      - auth-backend-app
    volumes:
      - ./app-storage:/app/app-storage
    networks:
      - toler-express-apps
    entrypoint: /bin/sh -c "sleep 10 && pnpm run dev"

networks:
  toler-express-apps:
    external: true

volumes:
  app-storage: